### PR TITLE
PAYARA-2396 Set properties via admin console now works

### LINKED ISSUE #2259: "An error occured" during editing of JDBC Connection Pool Properties
# Description #
----------

During editing of JDBC connection pool properties the error message "An error occured" is displayed after pressing "Save".

## Expected Outcome

Never ever make you application print "An error occured". All error messages of all possible inputs, configuration values or states of all applications need to provide helpful self-explanatory feedback!

## Current Outcome

grafik

and

    SCHWERWIEGEND:   RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/resources/jdbc-connection-pool/project1/property.json'; attrs = '[{"name":"Password","description":"","value":"a"},{"name":"PortNumber","description":"","value":"1527"},{"name":"Host","description":"","value":"localhost"},{"name":"User","description":"","value":"b"},{"name":"DatabaseName","description":"","value":"c"}]'

in `server.log` of `payaradomain`.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain payaradomain

2 -**  Create the Connection pool (all default properties are missing btw)

3 - ** Edit the properties as shown on the screenshot and click save

## Environment ##

- **Payara Version**: 5.0-beta2-20180112.004301-21
- **Edition**: Full
- **JDK Version**: 8 u151 - OpenJDK
- **Operating System**: Linux
- **Database**: Apache Derby 10.12.1.1

### PR DESCRIPTION
**Pull request by Cousjava**
fixes #2259

### CODE REVIEW

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 5 please

File: appserver/admingui/common/src/main/java/org/glassfish/admingui/common/gadget/GadgetHandlers.java [hunk 1]
```diff
@@ -234,24 +234,17 @@ public static Object invokeHandler(HandlerContext handlerCtx) {
...
 	handlerCtx.setHandler(oldHandler);
 
 	// Finally, translate the Map to JSON and set the String as an output
-	Integer depth = (Integer) handlerCtx.getInputValue("depth");
-	if (depth == null) {
-	    depth = 10;
-	}
-	handlerCtx.setOutputValue("values", JSONUtil.javaToJSON(outputValues, depth));
-
+        handlerCtx.setOutputValue("values",JsonUtil.getJsonValue(outputValues).toString());
```
Comment (Pandrex247) [inline appserver/admingui/common/src/main/java/org/glassfish/admingui/common/gadget/GadgetHandlers.java]: Missed a space (╯°□°）╯︵ ┻━┻

File: appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/JSONUtil.java [hunk 2]
```diff
@@ -710,13 +716,19 @@ char peekContextEnd() {
...
+                case COLON:
+                    val = ':';
+                    break;
+                case COMMA:
+                    val = ',';
+                    break;
+                case NULL:
+                    val = null;
+                    break;
+                default:
```
Comment (arjantijms) [inline appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/JSONUtil.java]: For switch on string, a default case is not really needed here, is it?

File: nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/MarshallingUtils.java [hunk 3]
```diff
@@ -77,12 +75,12 @@
         json = json.trim();
         if (json.startsWith("{")) {
             properties = new ArrayList<Map<String, String>>();
-            properties.add(processJsonMap(json));
+            properties.add(Util.processJsonMap(json));
```
Comment (arjantijms) [inline nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/MarshallingUtils.java]: You may want to statically import `Util.processJsonMap` here, as the fact that `processJsonMap` is now in a separate utility class doesn't really add much info to the reader who tries to understand this code.

File: nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/Util.java [hunk 4]
```diff
@@ -76,17 +88,37 @@
...
-                if (value instanceof JsonArray) {
-                    map.put(key, processJsonArray((JsonArray) value));
-                } else if (value instanceof JsonObject) {
-                    map.put(key, processJsonObject((JsonObject) value));
-                } else {
-                    map.put(key, value);
+                 JsonValue value = jo.get(key);
+                switch (value.getValueType()) {
+                    case ARRAY:
+                        map.put(key, processJsonArray((JsonArray) value));break;
```
Comment (arjantijms) [inline nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/Util.java]: One statement per line? break should be on the next line ;)

File: nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/Util.java [hunk 5]
```diff
@@ -76,17 +88,37 @@
...
+    /**
+     * Converts a {@link JsonObject} into a {@link Map}
+     * <p>
+     * The {@link Map} entries can be of types {@link Boolean}, {@link List},
+     * {@link Map}, {@link Number}, {@code null} and/or {@link String}.
+     * </p>
+     * @param jo
+     * @return 
+     */
     public static Map processJsonObject(JsonObject jo) {
```
Comment (arjantijms) [inline nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/Util.java]: Maybe rename "jo" into "jsonObject" or so? The former is not really clear in what it means ("jo" here is no common abbreviation)

File: nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/Util.java [hunk 6]
```diff
@@ -96,24 +128,42 @@ public static Map processJsonObject(JsonObject jo) {
...
+        
         try {
-            for (int i = 0; i < ja.size(); i++) {
-                Object entry = ja.get(i);
-                if (entry instanceof JsonArray) {
-                    results.add(processJsonArray((JsonArray) entry));
-                } else if (entry instanceof JsonObject) {
-                    results.add(processJsonObject((JsonObject) entry));
-                } else {
+            for (JsonValue entry: ja) {
```
Comment (arjantijms) [inline nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/Util.java]: "ja" could become "jsonArray" or so.

File: nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/MarshallingUtils.java (hunk 3 above)
Comment (Pandrex247) [reply nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/MarshallingUtils.java]: I hate statically imported methods! Methods should be in the class (or a parent one), not just grabbed from some random place at the top of the file.

Comment (arjantijms) [reply nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/MarshallingUtils.java]: You could ask yourself what the difference is between writing `java.lang.String` and `Util.processJsonMap` vs writing `String` and `processJsonMap`. In both cases the location they come from does not help with the readability.

The above example makes it even more clear. It was `processJsonMap` before. Then it became `Util.processJsonMap`. Does the latter make it really more clear to read?

Comment (Cousjava) [reply nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/MarshallingUtils.java]: Yes, especially since the method is no longer coming from the within the class, which it was previously. As there already was an identical method in another class in the same package it now uses that instead.

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by smillidge** [comment]
Jenkins, quick test Payara 5 please

**Comment by Cousjava** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Quick build and test passed!

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please

**Comment by arjantijms** [comment]
Jenkins, quick test Payara 5 please
