### PR TITLE
[FISH-1297] Certain network configurations lead to NPE on startup

### LINKED ISSUE #5192: Bug Report:  Payara 5.2021.2 *does not start* / FISH-1297
# Description #
----------

After creating a domain using `asadmin create-domain das`, trying to start it with `asadmin start-domain das` FAILS miserably.

The same result happens using the latest JDK 8 from Oracle, and the latest Zulu JDK 11.

Running on Centos 6.8 x86.

## Expected Outcome ##

The domain should start.

## Current Outcome ##

The domain *fails to start* and the output contains stack trace details.

## Steps to reproduce ## 

unpack the downloaded payara distribution zip file
configure payara5/glassfish/config/asenv.conf with AS_JAVA having location of java folder
navigate to payara5/glassfish/bin folder
issue command: ./asadmin create-domain das
issue command: ./asadmin start-domain das

see error output instead of result message indicating success.

In contrast, payara-5-2020.4.zip works just fine.

## Environment ##

- **Distribution**: Server Full Profile
- **JDK Version**: 8 u281 Oracle, OpenJDK, Zulu
- **Operating System**: Linux (centos 6.8)

### PR DESCRIPTION
**Pull request by lprimak**
## Description
This is a bug fix.
Certain network configurations lead to chosenAddress variable to be null and prevent Payara to start
Fixes #5192

### Testing Performed
Existing test suites

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test

File: nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java [hunk 1]
```diff
@@ -155,6 +155,14 @@ static InetSocketAddress initAddress(String address, int port) {
         }
     }
 
+    static InetAddress findMyAddressOrLocalHost() {
+        InetAddress myAddress = findMyAddress();
+        if (myAddress == null) {
+            return tryLocalHostOrLoopback(0).getAddress();
```
Comment (smillidge) [inline nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java:161]: Good do with a WARN or INFO log message at this point to the end user to indicate it is falling back to localhost as no suitable network address could be found.

Comment (lprimak) [reply nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java:161]: sure!

Comment (lprimak) [reply nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java:161]: Actually it already logs the error as part of `tryLocalHostOrLoopback()` so already taken care of :)

Comment (lprimak) [reply nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java:161]: I can change FINE log to WARNING in `tryLocalHostOrLoopback()`

**Comment by lprimak** [comment]
jenkins test

**Review by AlanRoth — APPROVED** [review]

**Review by smillidge — APPROVED** [review]
