### PR TITLE
PAYARA-2691 fix ResourceValidator Class Loaders

### LINKED ISSUE #2581: @Remote bean can't be accessed from a different app, when using Payara5
# Description #
----------

With the latest version of Payara 4 I am able to deploy the following two apps:

1. App1 has the following code(the below interface has single implementation):
```
import javax.ejb.Remote;

@Remote
public interface EmailNotificationManagerRemote {

	public void sendMail(String[] recipientsTo, String[] recipientsCC, String[] recipientsBCC, String subject,
            String body, String senderName, String senderMail, String mimeType, String mailSession, Boolean isSMS)
            throws InvalidInputException;
	
	 public void sendSupportMail(String errorCode, String subject, String body, String logLevel)  throws InvalidInputException;
}
```

App2 has the following code:

```
@EJB(mappedName="EmailNotificationManager")
private EmailNotificationManagerRemote emailNotificationManagerRemote;
```

When deploying App2(after App1 has already been successfully deployed), I get the following exception:

```
Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: JNDI lookup failed for the resource: Name: [java:module/env/com.***.KeyLicenseNotifierBean/emailNotificationManagerRemote], Lookup: [EmailNotificationManager#com.***.EmailNotificationManagerRemote], Type: [Session]
...
Caused by: javax.naming.CommunicationException: Communication exception for SerialContext[myEnv={java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is java.lang.RuntimeException: Cant copy Serializable object:]
...
Caused by: java.lang.RuntimeException: Cant copy Serializable object:
...
Caused by: java.lang.IllegalArgumentException: Illegal null argument to ObjectInputStreamWithLoader
```

## Expected Outcome

If App1 is successfully deployed, App2 should be deployed without exceptions.

## Current Outcome

App2 deployment fails.

## Steps to reproduce (Only for bug reports) 

Create two wars/jars one with a @Remote EJB definition and one which uses this remote bean. Check that when deploying the app, which uses the bean, the bean can't be found...

## Context (Optional)

The same two wars are deployable and are working on Payara4.

## Environment ##

- **Payara Version**: 5
- **Edition**:  Full
- **JDK Version**:  1.8.0_151
- **Operating System**:  Windows 10.0.15063 Build 15063

### PR DESCRIPTION
**Pull request by lprimak**
unset capturedInvocation (reset to null) if JNDI environment is not present,

signifying invalid invocation.  fixes #2581

### CODE REVIEW

**Comment by smillidge** [comment]
Can you check it in reference to https://github.com/payara/Payara/commit/b16f673dd19fc74924f088df5f4a2e23a743529d#diff-935446c41541b08168ed81591ca15470

**Comment by lprimak** [comment]
Looks good to me

**Comment by lprimak** [comment]
On second thought, the event AFTER_CLASSLOADER_CREATION the class loader is already set and JNDI environment isn't yet set up completely yet, so pushContext() is a no-op at this point.  Is there a particular reason that was needed?  Perhaps this is a vestage from Payara 4 where the application initialization was different

**Comment by lprimak** [comment]
@smillidge

**Comment by smillidge** [comment]
There was no  invocation which was causing an issue. This was the original issue I fixed. https://github.com/payara/Payara/issues/2430

**Comment by lprimak** [comment]
Thanks!  I'll re-test that one

**Comment by lprimak** [comment]
ok, added new setEmptyContext() to JavaEEContextUtil for this purpose, now works in both tickets

**Comment by lprimak** [comment]
jenkins test

File: appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java [hunk 1]
```diff
@@ -69,6 +69,14 @@
 @Service
 @PerLookup
 public class JavaEEContextUtilImpl implements JavaEEContextUtil, Serializable {
+    private transient @Getter(AccessLevel.PACKAGE) ServerContext serverContext;
+    private transient ComponentEnvManager compEnvMgr;
+    private transient ComponentInvocation capturedInvocation;
+    private @Getter(onMethod = @__(@Override)) String instanceComponentId;
```
Comment (Pandrex247) [inline appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java]: Unless I missed something we're still not allowing lombok.

Comment (lprimak) [reply appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java]: This has been there for a long time now.  I just changed the location as per coding standards.
I will get to making a massive PR in the future to remove lombok from everything so it can be correctly evaluated.
For now, please don't hold up a regression fix for this, I am just keeping the status quo for now, not adding new lombok code
