### PR TITLE
PAYARA-1966 Fix non-persistent timers with --nocluster

### LINKED ISSUE #1871: 'Problem when initialising Timer Store' on Payara Micro 173 with --noCluster
# Description #
----------
When running Payara Micro with `--noCluster` option deployment fails for application using non-persistent EJB Timer with following message:

```
[2017-08-16T22:24:15.451+0200] [] [WARNING] [AS-EJB-00053] [javax.enterprise.ejb.container] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915055451] [levelValue: 900] The feature use of persistent EJB Timer Service requires Full Java EE Profile to be supported

[2017-08-16T22:24:15.463+0200] [] [WARNING] [] [fish.payara.ejb.timer.hazelcast.HazelcastTimerStore] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915055463] [levelValue: 900] [[
  Problem when initialising Timer Store
java.lang.NullPointerException
	at fish.payara.ejb.timer.hazelcast.HazelcastTimerStore.<init>(HazelcastTimerStore.java:77)
	at fish.payara.ejb.timer.hazelcast.HazelcastTimerStore.init(HazelcastTimerStore.java:70)
	at fish.payara.ejb.timer.hazelcast.HazelcastEJBTimerService.initPersistentTimerService(HazelcastEJBTimerService.java:40)
	at com.sun.ejb.containers.EJBTimerService.initEJBTimerService(EJBTimerService.java:251)
	at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:215)
	at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:197)
	at com.sun.ejb.containers.BaseContainer.<init>(BaseContainer.java:773)
	at com.sun.ejb.containers.AbstractSingletonContainer.<init>(AbstractSingletonContainer.java:127)
	at com.sun.ejb.containers.CMCSingletonContainer.<init>(CMCSingletonContainer.java:76)
	at com.sun.ejb.containers.SingletonContainerFactory.createContainer(SingletonContainerFactory.java:68)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:225)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:290)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:100)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:209)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:318)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:488)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
	at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1396)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:993)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:361)
]]

[2017-08-16T22:24:15.465+0200] [] [INFO] [AS-EJB-00054] [javax.enterprise.ejb.container] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915055465] [levelValue: 800] Portable JNDI names for EJB NonPersistentTimer: [java:global/payara-timer-problem/NonPersistentTimer, java:global/payara-timer-problem/NonPersistentTimer!com.example.payara.NonPersistentTimer]

[2017-08-16T22:24:15.500+0200] [] [INFO] [] [org.jboss.weld.Version] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915055500] [levelValue: 800] WELD-000900: 2.4.2 (SP1)

[2017-08-16T22:24:15.747+0200] [] [INFO] [] [org.jboss.weld.Event] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915055747] [levelValue: 800] WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.

[2017-08-16T22:24:16.172+0200] [] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915056172] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
java.lang.RuntimeException: EJB Timer Service is not available
	at com.sun.ejb.containers.BaseContainer.startApplication(BaseContainer.java:3952)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:166)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:501)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:488)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
	at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1396)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:993)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:361)
]]

[2017-08-16T22:24:16.173+0200] [] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915056173] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.RuntimeException: EJB Timer Service is not available
	at com.sun.ejb.containers.BaseContainer.startApplication(BaseContainer.java:3952)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:166)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:501)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:488)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
	at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1396)
	at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:993)
	at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
	at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
	at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:361)
]]

[2017-08-16T22:24:16.173+0200] [] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915056173] [levelValue: 1000] Exception while loading the app

[2017-08-16T22:24:16.175+0200] [] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1502915056175] [levelValue: 1000] Undeployment failed for context /payara-timer-problem
```

## Expected Outcome

When working in `--noCluster` mode (without Hazelcast) it should still be possible to use non-persistent EJB timers. This configuration works fine with Payara Micro 163.

## Steps to reproduce

1. Create minimal JEE7 app with non-persistent timer like this:
```
import javax.ejb.Schedule;
import javax.ejb.Singleton;
import javax.ejb.Timeout;
import javax.ejb.Timer;

@Singleton
public class NonPersistentTimer {

	@Schedule(hour = "2", persistent = false)
	public void timerAction() {
		System.out.println("Timer action!");
	}

	@Timeout
	public void timeout(Timer timer) {
		System.out.println("Timeout!");
	}

}
```
2. Start Payara Micro with `--noCluster` options like this:
```
java -Xmx512m -jar payara-micro-4.1.2.173.jar --port 9090 --noCluster --deploy target/payara-timer-problem.war
```
3. Deployment fails as described above.

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Micro
- **JDK Version**: 8 u144- Oracle
- **Operating System**: Linux

### PR DESCRIPTION
**Pull request by smillidge**
Fixes #1871

### CODE REVIEW

**Comment by Pandrex247** [comment]
Jenkins test please

File: appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastEJBTimerService.java [hunk 1]
```diff
@@ -37,7 +59,7 @@ and Distribution License("CDDL") (collectively, the "License").  You
 
     @Override
     public void initPersistentTimerService(String target) {
-        HazelcastTimerStore.init(hazelcast);
+            HazelcastTimerStore.init(hazelcast);
```
Comment (Pandrex247) [inline appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastEJBTimerService.java]: Formatting mistake?

File: appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java [hunk 2]
```diff
@@ -67,7 +88,7 @@ and Distribution License("CDDL") (collectively, the "License").  You
 
     static void init(HazelcastCore core) {
         try {
-            EJBTimerService.setEJBTimerService(new HazelcastTimerStore(core));
+                EJBTimerService.setEJBTimerService(new HazelcastTimerStore(core));
```
Comment (Pandrex247) [inline appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java]: And again
