### PR TITLE
FISH-37 URL in DataSourceDefinition overrides serverName

### LINKED ISSUE #4385: faulty url in @DataSourceDefinition /FISH-37
## Issue

The `@DataSourceDefinition` provides the `url` property, but it will be ignored. If the the url is set to `jdbc:postgres://database:5432/demo`, a connection to `localhost:5432` will be established. The same settings work great by setting them as `serverName`, `portNumber` and `databaseName` directly.

## Demo

A small demo project to illustrate this behaviour can be found at https://github.com/ThomasPr/DataSourceDefinition

### working example ✅

The properties `serverName`, `portNumber` and `databaseName` are set individually. A connection to postgres at `database:5432` will be established successfully.

```java
@DataSourceDefinition(
    name = "java:global/jdbc/DemoDataSource",
    className = "org.postgresql.ds.PGSimpleDataSource",
    serverName = "database",  // set the property
    portNumber = 5432,        // set the property
    databaseName = "demo",    // set the property
    user = "demo",
    password = "demo")
```

### failing example ❌

The same settings from the working example will be used again, but this time, only the `url` property will be set. The result is a connection attempt to `localhost:5432` instead of `database:5432`

```java
@DataSourceDefinition(
    name = "java:global/jdbc/DemoDataSource",
    className = "org.postgresql.ds.PGSimpleDataSource",
    url = "jdbc:postgresql://database:5432/demo",  // only use url, but no serverName, portNumber or databaseName
    user = "demo",
    password = "demo")
```

### strange example 🔥

The same url-setting is used like in the failing example. But the `serverName`, `portNumber` and `databaseName` are set to empty values. Very strange: This time a connection to `database:5432` will be established successfully. The only difference to the failing example are the mentioned three empty values.

```java
@DataSourceDefinition(
    name = "java:global/jdbc/DemoDataSource",
    className = "org.postgresql.ds.PGSimpleDataSource",
    url = "jdbc:postgresql://database:5432/demo",  // use the url to configure connection properties
    user = "demo",
    password = "demo",
    serverName = "",    // set it to an empty value
    portNumber = -1,    // set it to an empty value
    databaseName = "")  // set it to an empty value
```

## Exception

During startup of Payara, the following Exception will occur in the failing case:

```
microservice_1  | [2019-12-13T14:29:00.071+0000] [] [SEVERE] [] [org.eclipse.persistence.session./file:/tmp/payaramicro-rt7729847129244438567tmp/applications/ROOT/WEB-INF/classes/_demo.ejb] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1576247340071] [levelValue: 1000] [[
microservice_1  |
microservice_1  | Local Exception Stack:
microservice_1  | Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.DatabaseException
microservice_1  | Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
microservice_1  | Error Code: 0
microservice_1  | 	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:318)
microservice_1  | 	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:150)
microservice_1  | 	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:172)
microservice_1  | 	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:233)
microservice_1  | 	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:815)
...
```

## Environment ##

- **Payara Version**: 5.194
- **Edition**: micro
- **JDK Version**: Zulu OpenJDK 8
- **Operating System**: Alpine Linux
- **Database**: Postgres

### PR DESCRIPTION
**Pull request by Cousjava**
## Description
This is a bug fix.

If URL has been set it should override the serverName, causing that to be set to null
to prevent that being using when the DataSource is initialised

Fixes #4385

### New tests
New test added in PR, DataSource Definition Tests

### Testing Performed
* Written test
* Debugging Payara and checking the value of serverName is set to null and unused
* Docker test in original issue

### Testing Environment
Zulu JDK 1.8_262 on Ubuntu 20.04 with Maven 3.6.3

### CODE REVIEW

File: appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/deployment/annotation/handlers/DataSourceDefinitionHandler.java [hunk 1]
```diff
@@ -394,11 +394,12 @@ private DataSourceDefinitionDescriptor createDescriptor(DataSourceDefinition def
             desc.setDatabaseName(defn.databaseName());
         }
 
-        if ((desc.getPortNumber() != -1 && desc.getDatabaseName() != null && desc.getServerName() != null)) {
+        if (desc.getPortNumber() != -1 && desc.getDatabaseName() != null && desc.getServerName() != null) {
             //standard properties are set, ignore URL
         } else {
             if (defn.url() != null && !defn.url().equals("")) {
                 desc.setUrl(defn.url());
+                desc.setServerName(null); //To prevent serverName overriding the URL, always use the URL if the standard properties are not set
```
Comment (Pandrex247) [inline appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/deployment/annotation/handlers/DataSourceDefinitionHandler.java:402]: Can you make a small change to the `DataSourceDefinitionDescriptor.setServerName(String serverName)` method please to reflect this.

That method sets a boolean of `serverNameSet` to true, which when you're setting it to null probably shouldn't be the case :)

**Review by Pandrex247 — CHANGES_REQUESTED** [review]

**Review by Pandrex247 — APPROVED** [review]

**Comment by jGauravGupta** [comment]
jenkins test please
