### PR TITLE
[FISH-1019] GlassFishProperties fix by @bhanuunrivalled

### LINKED ISSUE #4657: GlassFishProperties throws NPE if the Properties is null.
# Description #
----------

The properties class org.glassfish.embeddable.GlassFishProperties could silently be corrupt if initialized with a null Properties object.

## Steps to reproduce (Only for bug reports) 

The following instantiation would not produce any warning...

```
java.util.Properties properties0 = null;
org.glassfish.embeddable.GlassFishProperties glassFishProperties1 = new org.glassfish.embeddable.GlassFishProperties(properties0);
```

However, when you try to use any of the GlassFishProperties, you'd get NullPointerException.
E.g.:
```
glassFishProperties1.setConfigFileURI("path/to/config/file");
```

Therefore, constructors of GlassFishProperties should check for a null Properties object
or at least document the above behavior in the documentation.

### PR DESCRIPTION
**Pull request by lprimak**
Thank you @bhanuunrivalled for your fix
Incorporates PR #4917

Fixes #4657

### CODE REVIEW

**Comment by lprimak** [comment]
jenkins test

**Comment by lprimak** [comment]
@bhanuunrivalled I could not push my changes on top of your PR so I created my own

**Review by Pandrex247 — APPROVED** [review]
Haven't tested but LGTM - "what could go wrong?"

**Comment by lprimak** [comment]
jenkins test

File: nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java [hunk 1]
```diff
@@ -74,8 +76,10 @@ public GlassFishProperties() {
      * for the plugged in {@link GlassFishRuntime} (if any)
      *
      * @param props Properties object which will back this GlassFishProperties object.
+     * @throws NullPointerException if props is null
      */
     public GlassFishProperties(Properties props) {
+        Objects.requireNonNull(props);
```
Comment (dmatej) [inline nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java:82]: With an error message it would be beautiful ... I know this NPE thrown a bit later for years! :smiling_imp: 
Btw copyright 2017 - is it correct?

**Review by dmatej — APPROVED** [review]

File: nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java (hunk 1 above)
Comment (lprimak) [reply nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java:82]: I think there is a default error message that's there even if not specified

Comment (lprimak) [reply nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java:82]: I was wrong :)

**Comment by lprimak** [comment]
jenkins test

**Review by dmatej — APPROVED** [review]

File: nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java (hunk 1 above)
Comment (sgflt) [reply nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java]: Since JDK 14 https://openjdk.java.net/jeps/358
