### PR TITLE
PAYARA-3267 Fixing memory-wastage with JavaEETransactionImpl

### LINKED ISSUE #3396: Memory wastage - JavaEETransactionImpl
# Description #
----------
Java EE Transactions - after a transaction has been successfully completed (state == 3), it is not eligible for garbage collection until it times out (300 seconds by default on Payara). On large enterprise applications with lots of users calling lots of EJB methods, this can easily occupy lots of heap space unnecessarily (10GB+). It is not really a memory leak, because it will eventually be reclaimed, but it is an issue because heap space is occupied unnecessarily for quite a while. This issue can have a noticeable impact on high volume applications.

Glassfish issue:
https://github.com/eclipse-ee4j/glassfish/issues/21565

## Expected Outcome
JavaEETranactionImpl objects should be eligible for Garbage Collection once it is done executing (state == 3) OR after it timed out (Whichever comes first)

Alternatively, as a workaround, create an annotation similar to org.jboss.ejb3.annotation.TransactionTimeout or weblogic.javaee.TransactionTimeoutSeconds so that we can set the default Transaction timeout to 20 seconds, but have the option to extend it for certain methods with this new annotation.

## Current Outcome
JavaEETranactionImpl objects are only eligible for Garbage Collection once it timed out, even if it completed a while ago already.

## Steps to reproduce (Sample)
[HeapSpaceApp.zip](https://github.com/payara/Payara/files/2563261/HeapSpaceApp.zip)

Compile (maven) and run the attached source on production domain (Payara 5.183).
Make sure that the Transaction Timout matches the setting in Payara (300) by default.
Open http://localhost:8080/HeapSpaceApp/

What you can expect:
image

Note the results:
**Before start:** 
Time: 21:20:25 Used Memory: 747.2 MB

**After transactions created.**
Time: 21:20:27 Used Memory: 1.1 GB

**After possible GC:**
Time: 21:20:29 Used Memory: 796.3 MB
Heap Dump:

**Waiting 5 minutes for transactions to time out. Will refresh automatically...
After possible GC after waiting 5 minutes for all transactions to expire.**
Time: 21:25:35 Used Memory: 752.0 MB
Heap dump:

Estimated heap space wasted for 5 minutes: **44.8 MB** (According to heap dump it's actually 10 MB)
You will see that all the generated records are still available (in bean property as list) at this point in time, just the JavaEETransactionImpl objects were Garbage-collected.

## Environment ##

- **Payara Version**: 5.183
- **Edition**: Full
- **JDK Version**: 8 u181 - Oracle
- **Operating System**: Windows

### PR DESCRIPTION
**Pull request by svendiedrichsen**
Replacing usage of java.util.Timer/TimerTask with PayaraExecutorService/ScheduledExecutorService which is configured to remove cancelled tasks immediately.

This should fix #3396

### CODE REVIEW

**Comment by arjantijms** [comment]
Jenkins test please

File: nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java [hunk 1]
```diff
@@ -117,93 +117,94 @@ public void event(Event event) {
...
+                    Integer.valueOf(payaraExecutorServiceConfiguration.getThreadPoolExecutorMaxPoolSize()),
+                    Integer.valueOf(payaraExecutorServiceConfiguration.getThreadPoolExecutorKeepAliveTime()),
                     TimeUnit.valueOf(payaraExecutorServiceConfiguration.getThreadPoolExecutorKeepAliveTimeUnit()),
                     new SynchronousQueue<>(), (Runnable r) -> new Thread(r, "payara-executor-service-task"));
         }
 
         scheduledThreadPoolExecutor = new ScheduledThreadPoolExecutor(
                 Integer.valueOf(payaraExecutorServiceConfiguration.getScheduledThreadPoolExecutorCorePoolSize()),
                 (Runnable r) -> new Thread(r, "payara-executor-service-scheduled-task"));
+        scheduledThreadPoolExecutor.setRemoveOnCancelPolicy(true);
```
Comment (smillidge) [inline nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java]: I think this should be configurable on the service

Comment (smillidge) [reply nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java]: Also I think the old purge on x number of tasks should be also retained in case there is a performance hit on removing the tasks for many small and rapid transactions like in high volume web applications with timeouts enabled.

File: appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java [hunk 2]
```diff
@@ -109,11 +112,13 @@
     @Inject protected InvocationManager invMgr;
 
     @Inject private Provider<RequestTracingService> requestTracing;
-    
+
+    @Inject private PayaraExecutorService payaraExecutorService;
```
Comment (smillidge) [inline appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java]: I don't think Payara Executor Service should be used for this. This is core application processing logic and I feel this could overload the Payara Executor Service which was planned for more internal tasks. For example if you have a web application performing 100s of requests per second with timeouts enabled we could be adding and removing 100s of timeout tasks per second on this Executor Pool. I approve of replacing timer with the more modern executor service though.

File: nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java (hunk 1 above)
Comment (svendiedrichsen) [reply nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java]: Removed config from PayaraExecutorService

**Comment by svendiedrichsen** [comment]
@smillidge Implemented your requested changes. Maybe the `production` domain configuration Payara comes with should set a sensible default value for the transaction service property `purge-cancelled-transactions-after` to lower memory usage.

**Comment by svendiedrichsen** [comment]
@smillidge Nice to see you going all-in on the PayaraExecutorService. Using it everywhere now. ;)

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by lprimak** [comment]
jenkins test

**Comment by svendiedrichsen** [comment]
Resolved merge conflicts

File: appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java (hunk 2 above)
Comment (svendiedrichsen) [reply appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java]: Replaced PayaraExecutorService with newly created ScheduledThreadPoolExecuter

**Comment by arjantijms** [comment]
Jenkins test please

**Comment by Pandrex247** [comment]
Fixes https://github.com/payara/Payara/issues/3396
