### PR TITLE
FISH-10049 bugfix: Split CDI bean deployment when multiple WARs exist in an EAR

### LINKED ISSUE #7031: Bug Report: EAR application deployment with CDI fails
### Brief Summary

Deploying a simple EAR class who's constituent WARs use CDI fails deployment process

### Expected Outcome

Deployment succeeds

### Current Outcome

```
[#|2024-10-17T14:37:10.889-0500|SEVERE|Payara 6.2024.11|javax.enterprise.system.core|_ThreadID=108;_ThreadName=admin-thread-pool::admin-listener(1);_TimeMillis=1729193830889;_LevelValue=1000;_MessageID=NCLS-CORE-00026;|
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:javax.naming.NamingException: Lookup failed for 'java:comp/BeanManager' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NamingException: Error retrieving java:comp/BeanManager [Root exception is java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null]] -- javax.naming.NamingException: Lookup failed for 'java:comp/BeanManager' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NamingException: Error retrieving java:comp/BeanManager [Root exception is java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null]]
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:38)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:501)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:94)
	at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:582)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:437)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:135)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:344)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:580)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.base/jdk.internal.vm.ScopedValueContainer.callWithoutScope(ScopedValueContainer.java:162)
	at java.base/jdk.internal.vm.ScopedValueContainer.call(ScopedValueContainer.java:147)
	at java.base/java.lang.ScopedValue$Carrier.call(ScopedValue.java:420)
	at java.base/java.lang.ScopedValue.callWhere(ScopedValue.java:568)
	at java.base/javax.security.auth.Subject.callAs(Subject.java:439)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:521)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.base/jdk.internal.vm.ScopedValueContainer.callWithoutScope(ScopedValueContainer.java:162)
	at java.base/jdk.internal.vm.ScopedValueContainer.call(ScopedValueContainer.java:147)
	at java.base/java.lang.ScopedValue$Carrier.call(ScopedValue.java:420)
	at java.base/java.lang.ScopedValue.callWhere(ScopedValue.java:568)
	at java.base/javax.security.auth.Subject.callAs(Subject.java:439)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:521)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:409)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:236)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:179)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:1575)
|#]
```

### Reproducer

https://github.com/flowlogix/ear-sample

Will see if it's simple enough and will try to issue a PR for this

### Operating System

Any

### JDK Version

Any

### Payara Distribution

Payara Server Full Profile

### LINKED ISSUE #7078: Bug Report: ClassLoader leak when Timer Service is used
### Brief Summary

I have noticed that any application that uses `@Scheduled` or programmatic equivalents,
basically any application that touches `TimerService` doesn't unload properly, caused by `ClassLoader` leak

### Expected Outcome

Application undeploys cleanly

### Current Outcome

Leaks are detected

### Reproducer

Not yet.

### Operating System

Any

### JDK Version

Any

### Payara Distribution

Payara Server Full Profile, Payara Server Web Profile, Payara Micro, Payara Embedded All, Payara Embedded Web, Payara Docker Image

### PR DESCRIPTION
**Pull request by lprimak**
## Description
Bugfix. BeanManager isn't properly constructed when multiple CDI WARs exist in an EAR.
Also allows EAR-libraries to be scanned for CDI annotations

fixes #7031 
also fixes #7078 
Appears specifically when multiple WARs use OmniFaces

## Important Info
This is the *head* PR in the CDI-performance and modernization sequence.
PRs #7165 and #7097 depend on this PR

## Testing
Tested with the failing reproducer
** Needs TCK run

### CODE REVIEW

**Comment by lprimak** [comment]
Jenkins test

**Comment by Pandrex247** [comment]
@lprimak I ran it through the CDI and EJB TCKs and all seems green 👍

**Comment by lprimak** [comment]
Thanks, Fantastic!
I gotta do a lot more testing on my end, but this is promising!

File: appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java [hunk 1]
```diff
@@ -467,139 +454,176 @@ public boolean is299Enabled(BundleDescriptor bundle) {
...
-        return appToBootstrap.get(app);
+    public WeldBootstrap getBootstrapForArchive(BeanDeploymentArchive archive) {
+        return ((BeanDeploymentArchiveImpl) archive).weldBootstrap;
     }
 
-
+    public String getContextIdForArchive(BeanDeploymentArchive archive) {
+        var impl = (BeanDeploymentArchiveImpl) archive;
+        String rootContextId = impl.getBeanDeploymentArchives().stream()
+                .filter(c -> c.getClass() == RootBeanDeploymentArchive.class)
```
Comment (lprimak) [inline appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java:464]: use `::isInstance`

**Comment by lprimak** [comment]
I have found a few issues that I found with "real" applications.
I think I worked through most of them, so stay tuned

**Comment by lprimak** [comment]
I may also roll a fix for #6405 if that's trivial as well

**Comment by lprimak** [comment]
Im getting close. "Real" application runs.

**Comment by lprimak** [comment]
Now I gotta fix the conflict :)

**Comment by lprimak** [comment]
Once the tests passes I am going to squash the commits and un-draft the PR again

**Comment by lprimak** [comment]
Ready to go again

File: appserver/web/war-util/pom.xml [hunk 2]
```diff
@@ -120,4 +120,20 @@
...
+
+    <build>
+        <plugins>
+            <plugin>
+                <groupId>com.github.siom79.japicmp</groupId>
+                <artifactId>japicmp-maven-plugin</artifactId>
+                <configuration>
+                    <parameter>
+                        <excludes>
+                            <exclude>org.glassfish.web.loader.CachingReflectionUtil</exclude>
```
Comment (kalinchan) [inline appserver/web/war-util/pom.xml:132]: I believe this will break semantic versioning, this will require reworking your changes.

Comment (lprimak) [reply appserver/web/war-util/pom.xml:132]: This is an internal class. It was moved into a different module.  Nothing should be affected.

Comment (Pandrex247) [reply appserver/web/war-util/pom.xml:132]: We'd strongly prefer that you keep changes in line with semantic versioning - no breaking changes on minor version updates.
Parts of the codebase are shared with Enterprise and extensions, the semantic versioning is in place to help ensure compilation and runtime errors don't unknowingly propagate. 

We'll need to make sure this class is not used in any of the non-shared codebase (not just in this repo) before allowing this breaking change to go through.

Comment (lprimak) [reply appserver/web/war-util/pom.xml:132]: I suppose I could deprecate it. More changes to this API are coming from #7097 so stay tuned for that anyway

Comment (lprimak) [reply appserver/web/war-util/pom.xml]: I have made the changes to deprecate the class and remove the `japicmp` exclusion
Thank you

**Comment by lprimak** [comment]
This one is the head of the backlog now

**Comment by luiseufrasio** [comment]
@lprimak I tried to run jenkins test again after your last update and it is not working

**Comment by lprimak** [comment]
The conflicts arose due to merging of #7163
I believe that's fixed now

**Review by luiseufrasio — CHANGES_REQUESTED** [review]
@lprimak I had 2 issues:

1. I could not build the reproducer on Windows 11, only on WSL (Ubuntu 22.04):
image

2. The deploy of `ear1-1.x-SNAPSHOT.ear` built in WSL works when running Payara Server on Windows 11 and on WSL, but when I launch the war applications it only works on WSL. On Windows 11 I had HTTP 500 error:
image

**Comment by lprimak** [comment]
I don't have windows so I really can't do anything about that. Not sure what the issue even may be

**Comment by lprimak** [comment]
Reproducer builds fine on Windows, as it looks like, but it won't run.
Use -Ppayara-server-local to skip payara startup.

As far as 500 error, I have no idea as I don't have windows. Do you have an exception at least?
I may need your help reproducing this if it's not trivial.

**Comment by luiseufrasio** [comment]
These are the log server, but it is not related to your application:

```
[#|2025-02-04T18:02:18.266-0300|INFO|Payara 6.2025.2|javax.enterprise.system.core|_ThreadID=245;_ThreadName=admin-thread-pool::admin-listener(2);_TimeMillis=1738702938266;_LevelValue=800;|
  ear1-1.x-SNAPSHOT was successfully deployed in 8,775 milliseconds.|#]

[#|2025-02-04T18:02:18.564-0300|SEVERE|Payara 6.2025.2|org.glassfish.admingui.common.util.JerseyRestResponse|_ThreadID=245;_ThreadName=admin-thread-pool::admin-listener(2);_TimeMillis=1738702938564;_LevelValue=1000;|
  Unsupported Response Format: 'text/html;charset=iso-8859-1'!|#]

[#|2025-02-04T18:02:18.565-0300|SEVERE|Payara 6.2025.2|org.glassfish.admingui|_ThreadID=245;_ThreadName=admin-thread-pool::admin-listener(2);_TimeMillis=1738702938565;_LevelValue=1000;|
  RestResponse.getResponse() gives FAILURE.  endpoint = 'http://local:4848/management/domain/nodes/node/localhost-domain1'; attrs = '{}'|#]

[#|2025-02-04T18:02:18.565-0300|INFO|Payara 6.2025.2|org.glassfish.admingui|_ThreadID=245;_ThreadName=admin-thread-pool::admin-listener(2);_TimeMillis=1738702938565;_LevelValue=800;|
  Exception Occurred :java.lang.RuntimeException: java.lang.RuntimeException: |#]
```

But a different error occurs when trying to undeploy:

```
[#|2025-02-04T18:09:26.413-0300|WARNING|Payara 6.2025.2|javax.enterprise.system.util|_ThreadID=299;_ThreadName=admin-thread-pool::admin-listener(4);_TimeMillis=1738703366413;_LevelValue=900;|
  ASURLClassLoader EarLibClassLoader :
doneCalled = true
doneSnapshot = ASURLClassLoader.done() called ON EarLibClassLoader :
urlSet = []
doneCalled = false
 Parent -> org.glassfish.internal.api.DelegatingClassLoader@57bf6309

 AT Tue Feb 04 18:09:26 GFT 2025
 BY :[java.base/java.lang.Thread.getStackTrace(Thread.java:2450), com.sun.enterprise.loader.ASURLClassLoader.done(ASURLClassLoader.java:205), com.sun.enterprise.loader.ASURLClassLoader.preDestroy(ASURLClassLoader.java:171), org
.glassfish.javaee.full.deployment.EarClassLoader.preDestroy(EarClassLoader.java:122), org.jvnet.hk2.internal.ServiceLocatorImpl.preDestroy(ServiceLocatorImpl.java:1068), org.jvnet.hk2.internal.ServiceLocatorImpl.preDestroy(Serv
iceLocatorImpl.java:1052), org.glassfish.internal.data.ApplicationInfo.clean(ApplicationInfo.java:490), com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1400), com.sun.enterprise.v3.server.Appl
icationLifecycle.undeploy(ApplicationLifecycle.java:1428), org.glassfish.deployment.admin.UndeployCommand.execute(UndeployCommand.java:431), com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556), com
.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552), java.base/java.security.AccessController.doPrivileged(AccessController.java:400), java.base/javax.security.auth.Subject.doAs(Subject.java:453), com
.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551), com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582), com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunne
rImpl.java:574), java.base/java.security.AccessController.doPrivileged(AccessController.java:400), java.base/javax.security.auth.Subject.doAs(Subject.java:453), com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRun
nerImpl.java:573), com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497), com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879), com.sun.enterprise.v3
.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755), org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:272), org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.
java:240), org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:294), org.glassfish.admin.rest.resources.TemplateRestResource.runCommand(TemplateRestResource.java:570), org.glassfish.admin.rest.resources.Tem
plateRestResource.doDelete(TemplateRestResource.java:307), org.glassfish.admin.rest.resources.TemplateRestResource.delete(TemplateRestResource.java:190), java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMe
thodHandleAccessor.java:103), java.base/java.lang.reflect.Method.invoke(Method.java:580), org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.
java:52), org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146), org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.inv
oke(AbstractJavaResourceMethodDispatcher.java:189), org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176), org.glassfish.jer
sey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93), org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478), org.glassfis
h.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400), org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81), org.glassfish.jersey.server.ServerRuntime$1.run(Se
rverRuntime.java:274), org.glassfish.jersey.internal.Errors$1.call(Errors.java:248), org.glassfish.jersey.internal.Errors$1.call(Errors.java:244), org.glassfish.jersey.internal.Errors.process(Errors.java:292), org.glassfish.jer
sey.internal.Errors.process(Errors.java:274), org.glassfish.jersey.internal.Errors.process(Errors.java:244), org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266), org.glassfish.jersey.server.Serv
erRuntime.process(ServerRuntime.java:253), org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696), org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
, org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:335), org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189), org.glassfish.admin.rest.adapter.RestManagementAdapter.service(RestMana
gementAdapter.java:66), com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520), com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217), org.glassfis
h.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174), org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153), org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.ja
va:202), org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88), org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246), org.glassfish.grizzly.filterchain
.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178), org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118), org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultF
ilterChain.java:96), org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51), org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510), org.glassfish.grizzly.strategies.Abstra
ctIOStrategy.fireIOEvent(AbstractIOStrategy.java:82), org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83), org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.ru
n(WorkerThreadIOStrategy.java:101), org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535), org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515), java.base/java.lang.Thread.run(Thread.java:1583)] Parent -> org.glassfish.internal.api.DelegatingClassLoader@57bf6309
 was requested to find class org.omnifaces.cdi.eager.EagerBeansRepository after done was invoked from the following stack trace
java.lang.Throwable
        at com.sun.enterprise.loader.ASURLClassLoader.findClassData(ASURLClassLoader.java:791)
        at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:704)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
```

**Comment by lprimak** [comment]
Yes, that doesn't look at all related.

**Comment by luiseufrasio** [comment]
> Yes, that doesn't look at all related.

@lprimak forget about the 1st issue regarding Windows 11, It was my local maven repo which was corrupted.

Now please try to reproduce the Undeploy issue on your local, because this one seems to be related to your changes:
image
As you can see in the image above it is very slow and into the logs we have:

```
[#|2025-02-06T09:47:21.455-0300|WARNING|Payara 6.2025.2|javax.enterprise.system.util|_ThreadID=302;_ThreadName=admin-thread-pool::admin-listener(3);_TimeMillis=1738846041455;_LevelValue=900;|
  ASURLClassLoader EarLibClassLoader :
doneCalled = true
doneSnapshot = ASURLClassLoader.done() called ON EarLibClassLoader :
urlSet = []
doneCalled = false
 Parent -> org.glassfish.internal.api.DelegatingClassLoader@2437c706

 AT Thu Feb 06 09:47:21 GFT 2025
 BY :[java.base/java.lang.Thread.getStackTrace(Thread.java:2450), com.sun.enterprise.loader.ASURLClassLoader.done(ASURLClassLoader.java:205), com.sun.enterprise.loader.ASURLClassLoader.preDestroy(ASURLClassLoader.java:171), org
.glassfish.javaee.full.deployment.EarClassLoader.preDestroy(EarClassLoader.java:122), org.jvnet.hk2.internal.ServiceLocatorImpl.preDestroy(ServiceLocatorImpl.java:1068), org.jvnet.hk2.internal.ServiceLocatorImpl.preDestroy(Serv
iceLocatorImpl.java:1052), org.glassfish.internal.data.ApplicationInfo.clean(ApplicationInfo.java:490), com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1400), com.sun.enterprise.v3.server.Appl
icationLifecycle.undeploy(ApplicationLifecycle.java:1428), org.glassfish.deployment.admin.UndeployCommand.execute(UndeployCommand.java:431), com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556), com
.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552), java.base/java.security.AccessController.doPrivileged(AccessController.java:400), java.base/javax.security.auth.Subject.doAs(Subject.java:453), com
.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551), com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582), com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunne
rImpl.java:574), java.base/java.security.AccessController.doPrivileged(AccessController.java:400), java.base/javax.security.auth.Subject.doAs(Subject.java:453), com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRun
nerImpl.java:573), com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497), com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879), com.sun.enterprise.v3
.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755), org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:272), org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.
java:240), org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:294), org.glassfish.admin.rest.resources.TemplateRestResource.runCommand(TemplateRestResource.java:570), org.glassfish.admin.rest.resources.Tem
plateRestResource.doDelete(TemplateRestResource.java:307), org.glassfish.admin.rest.resources.TemplateRestResource.delete(TemplateRestResource.java:190), java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMe
thodHandleAccessor.java:103), java.base/java.lang.reflect.Method.invoke(Method.java:580), org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.
java:52), org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146), org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.inv
oke(AbstractJavaResourceMethodDispatcher.java:189), org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176), org.glassfish.jer
sey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93), org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478), org.glassfis
h.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400), org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81), org.glassfish.jersey.server.ServerRuntime$1.run(Se
rverRuntime.java:274), org.glassfish.jersey.internal.Errors$1.call(Errors.java:248), org.glassfish.jersey.internal.Errors$1.call(Errors.java:244), org.glassfish.jersey.internal.Errors.process(Errors.java:292), org.glassfish.jer
sey.internal.Errors.process(Errors.java:274), org.glassfish.jersey.internal.Errors.process(Errors.java:244), org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266), org.glassfish.jersey.server.Serv
erRuntime.process(ServerRuntime.java:253), org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696), org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
, org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:335), org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189), org.glassfish.admin.rest.adapter.RestManagementAdapter.service(RestMana
gementAdapter.java:66), com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520), com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217), org.glassfis
h.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174), org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153), org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.ja
va:196), org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88), org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246), org.glassfish.grizzly.filterchain
.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178), org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118), org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultF
ilterChain.java:96), org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51), org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510), org.glassfish.grizzly.strategies.Abstra
ctIOStrategy.fireIOEvent(AbstractIOStrategy.java:82), org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83), org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.ru
n(WorkerThreadIOStrategy.java:101), org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535), org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515), java.base/java.lang.Thread.run(Thread.java:1583)] Parent -> org.glassfish.internal.api.DelegatingClassLoader@2437c706
 was requested to find class org.omnifaces.cdi.eager.EagerBeansRepository after done was invoked from the following stack trace
java.lang.Throwable
        at com.sun.enterprise.loader.ASURLClassLoader.findClassData(ASURLClassLoader.java:791)
        at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:704)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at com.sun.enterprise.loader.CachingReflectionUtil.lambda$getClassFromCache$0(CachingReflectionUtil.java:61)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at com.sun.enterprise.loader.CachingReflectionUtil.getClassFromCache(CachingReflectionUtil.java:59)
        at com.sun.enterprise.loader.CacheCleaner.clearOmniFacesCache(CacheCleaner.java:79)
        at com.sun.enterprise.loader.CacheCleaner.clearCaches(CacheCleaner.java:51)
        at com.sun.enterprise.loader.ASURLClassLoader.done(ASURLClassLoader.java:211)
        at com.sun.enterprise.loader.ASURLClassLoader.preDestroy(ASURLClassLoader.java:171)
        at org.glassfish.javaee.full.deployment.EarClassLoader.preDestroy(EarClassLoader.java:122)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.preDestroy(ServiceLocatorImpl.java:1068)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.preDestroy(ServiceLocatorImpl.java:1052)
        at org.glassfish.internal.data.ApplicationInfo.clean(ApplicationInfo.java:490)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1400)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.undeploy(ApplicationLifecycle.java:1428)
        at org.glassfish.deployment.admin.UndeployCommand.execute(UndeployCommand.java:431)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:453)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:453)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:272)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:240)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:294)
        at org.glassfish.admin.rest.resources.TemplateRestResource.runCommand(TemplateRestResource.java:570)
        at org.glassfish.admin.rest.resources.TemplateRestResource.doDelete(TemplateRestResource.java:307)
        at org.glassfish.admin.rest.resources.TemplateRestResource.delete(TemplateRestResource.java:190)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
        at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:335)
        at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189)
        at org.glassfish.admin.rest.adapter.RestManagementAdapter.service(RestManagementAdapter.java:66)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:1583)
|#]
```

**Comment by lprimak** [comment]
I was able to reproduce the problem. It seems I forgot to re-test my sample app, just more sophisticated ones,
which for some reason, don't have the same issue :) Thanks for checking!
Should be an easy fix. Stay tuned.

**Comment by lprimak** [comment]
@luiseufrasio Fixed. Thank you

**Review by luiseufrasio — APPROVED** [review]
LGTM! Deploy and Undeploy are ok now. I also did the manual tests and they worked well.
