### PR TITLE
PAYARA-5496  fixing RwLockDatastructure locking bug (also FISH-985)

### LINKED ISSUE #5496: Bug Report:  RWLockDataStructure may leave a read lock /FISH-5858
# Description #
----------

The class RWLockDataStructure has a flawed lock handling which may result in a read lock not being unlocked. This freezes any thread trying to get a write lock.

https://github.com/payara/Payara/blob/master/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java

The method removeAll() clears the resources list outside of write lock (line 204).  Which seems redundant anyway.

```
    public void removeAll() {
        writeLock.lock();
        try {
            Iterator it = resources.iterator();
            while (it.hasNext()) {
                handler.deleteResource((ResourceHandle) it.next());
                it.remove();
            }
        } finally {
            writeLock.unlock();
        }
        resources.clear(); // redundant and removes eventually freshly created resources without properly deleting
    }
```

If this happens while some other thread calls the method getResource() (at line 118) then the resulting IndexOutOfBoundsException prevents unlocking the currently held read lock. The code is lacking some finally block to unlock the readlock.

```
    public ResourceHandle getResource() {
        readLock.lock();
        for(int i=0; i<resources.size(); i++){
            ResourceHandle h = resources.get(i); // this will cause an exception if the code above has cleared the list
            if (!h.isBusy()) {
                readLock.unlock();
                writeLock.lock();
                try {
                    if (!h.isBusy()) {
                        h.setBusy(true);
                        return h;
                    } else {
                        readLock.lock();
                        continue;
                    }
                }finally {
                    writeLock.unlock();
                }
            } else {
                continue;
            }
        }
        readLock.unlock(); // this should be in a finally block to prevent lost read locks
        return null;
    }
```

## Expected Outcome ##

All aquired locks will always be unlocked.

## Current Outcome ##

If the aquired read lock is not returned in case an exception is thrown at line 118 the RWLockDataStructure stays read locked and the server starts to block all threads trying the aquire a write lock.

## Steps to reproduce ## 

As always with race conditions it is not that simple to predictably provoke this situation. But the code is simple enough to spot the problem.

## Environment ##

- **Distribution**: 5.2020.5 Full
- **JDK Version**: OpenJDK 11
- **Operating System**: Linux

### PR DESCRIPTION
**Pull request by svendiedrichsen**
## Description
This fixes a lost read lock in RWLockDataStructure in case removeAll() is called while other threads call getResource().
fixes #5496

### New tests
No new tests created

### Testing Performed
Testing could be done by simulation heavy db access load.

## Notes for Reviewers
There were notes about some coarse lock handling in method addResource(...) which as been adapted according to lock handling in getResource() method

### CODE REVIEW

**Review by OndroMih — APPROVED** [review]
Looks good. I don't see why it wouldn't work, it actually looks much better than before. I think that it also improves performance when the connection pool is configured to create multiple connections at once because the pool no longer needs to wait until the whole batch is created but connections can be assigned to other threads even before the whole batch is finished.

File: appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java [hunk 1]
```diff
@@ -59,52 +62,52 @@
...
     /**
      * {@inheritDoc}
      */
     public int addResource(ResourceAllocator allocator, int count) throws PoolingException {
         int numResAdded = 0;
-        writeLock.lock();
-        //for now, coarser lock. finer lock needs "resources.size() < maxSize()" once more.
+        readLock.lock();
         try {
             for (int i = 0; i < count && resources.size() < maxSize; i++) {
```
Comment (sgflt) [inline appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java:91]: Nitpicking: Is following construction possible?

```java
            for (int i = 0; i < count && doLockSecured(this::isNotFull, readLock); i++) {
                writeLock.lock();
                try {
                    if (isNotFull()) {
                        ResourceHandle handle = handler.createResource(allocator);
                        resources.add(handle);
                        numResAdded++;
                    }                  
                } catch (Exception e) {
                    PoolingException pe = new PoolingException(e.getMessage());
                    pe.initCause(e);
                    throw pe;
                } finally {
                    writeLock.unlock();
                }
             }
```

At first glance it improves writelock downgrade, which is in this case possible unnecessary. Am I right?

Comment (sgflt) [reply appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java:91]: 2nd version:

```java
 for (int i = 0; i < count && doLockSecured(this::isNotFull, readLock); i++) {
         numResourcesAdded += doLockSecured(this::addResourceInternal, writeLock);
 }
```

Comment (svendiedrichsen) [reply appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java:91]: In IMHO it would be best not to create the resource within the write lock. But rather create it before without lock then try to add it write locked and if this does not succeed destroy it again.
```
 for (int i = 0; i < count && doLockSecured(this::isNotFull, readLock); i++) {
         final  ResourceHandle handle = handler.createResource(allocator);
         boolean added = doLockSecured(() -> addResourceInternal(handle), writeLock);
         if (added) {
             numResourcesAdded++;
         } else {
             handler.removeResource(handle);
         }
 }
``` 
This way the DS is not locked during connection time resulting in higher throughput overall.

Comment (fturizo) [reply appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java:91]: I agree with @svendiedrichsen, as in this way, the resource's creation outside the write lock's scope will lead to better performance, especially when a batch of connections is being requested by the associated pool to each resource.

**Comment by svendiedrichsen** [comment]
@fturizo @sgflt I have adapted the code of the `addResource()` method according to the resolved discussion outcome.

**Comment by fturizo** [comment]
jenkins test please

**Comment by svendiedrichsen** [comment]
@fturizo @aubi I have refactored the `getResource()` to use a separate Deque for managment of free resources.

**Comment by aubi** [comment]
Here is my reproducer - simple REST app with access to a database (db tasks, username+password tasks, table task with 1 row)
[PerformanceReproducer.zip](https://github.com/payara/Payara/files/7579412/PerformanceReproducer.zip)
Commands to setup Payara:
```
./asadmin start-domain
./asadmin add-library /usr/share/java/postgresql.jar
./asadmin create-jdbc-connection-pool --datasourceclassname org.postgresql.ds.PGSimpleDataSource --driverclassname org.postgresql.Driver --restype javax.sql.DataSource --property user=
tasks:password=tasks:URL="jdbc\:postgresql\://localhost/tasks" tasksPool
./asadmin ping-connection-pool tasksPool
./asadmin create-jdbc-resource --connectionpoolid tasksPool jdbc/tasks
./asadmin set configs.config.server-config.thread-pools.thread-pool.http-thread-pool.max-thread-pool-size=50
./asadmin stop-domain
```
Application testing many accesses (current settings total 1.000 tasks in 100 threads, 10 requests/task):
[PerformanceReproducerTester.zip](https://github.com/payara/Payara/files/7579413/PerformanceReproducerTester.zip)

**Comment by aubi** [comment]
Commits to 87ec3c68fb85fd1961b84ca0206673e759809e5e (doing the lock downgrade...):
Fine, I totally agree, code is much simpler and cleaner.

Commits to 1433844d72c14c2055af1583879436e7f3ee0a01 (refactoring code according...):
This speeds start up, but some resources are created and immediately removed. I can imagine, that this may cause problems, e.g. when only limited number of connections are allowed to a database -- some requests may fail.

I made a modification, when only one thread is allowed to add resource. It is a bit slower (not significantly), doesn't waste resources: https://github.com/aubi/Payara/tree/single-thread-addresource
I prefer this version.

Changes from 958fef8ba8312fe2c404b493c2393452336d6a05 (improving on handling free...):
I'm not sure the freeResources help. It removes for-cycle, but doesn't improve performance (by my measurements) and need more careful review.

**Comment by svendiedrichsen** [comment]
@aubi The freeResources Deque alos improves on the way connections are taken and used. Working with the list it distibutes the usage more over the whole list of connections which prevents idle connection reclaim.

**Comment by aubi** [comment]
I rebased my change (single thread addResource) to the latest commits. Before going final, it will require a bit code cleanup (removing the additional deleteResource). https://github.com/aubi/Payara/commit/89ea7d71b230b84ac3df6836849c7f1d1a175d02
Commits in this PR are good except the speculative allocation. I accept this PR with the modification.

**Comment by pdudits** [comment]
I offer solution to making speculative allocation non-speculative.

Every thread that executes `addResource` is guaranteed that when `canGrow` returns true the pool would not exceed its maxSize.

Before check every thread would increment `inflightCreates` and decrement it after it finishes. Oh I need to fix the boundary, it should now read `<=`. I'll be back :)

**Comment by svendiedrichsen** [comment]
@pdudits Very nice solution. I shall remember this one.

**Comment by svendiedrichsen** [comment]
@pdudits After some time thinking about it I think you should either do the inflight increase within the loop or increase by `count`. Otherwise two threads coming in with `count` > 1 could grow the pool beyond it maxSize.

**Comment by pdudits** [comment]
@svendiedrichsen welcome to the club! We're just in chat with @aubi and found the same thing and then every other workaround has some other issue

The sad truth is, that `count` is always `1`, but we want to keep this API, so I'll try another approach with a semaphore.

**Comment by pdudits** [comment]
I couldn't, there were large consistency gaps and they are very hard to explain in written form (I should learn TLA+ to be able to express these)

let's say that remaining capacity is 1 and two threads want to grow:
```
T1                  T2
---------------------------
increment      increment
canGrow        canGrow
  == false        == false
```

No connection will be added even when there's capacity.

Increase/decrease by 1 has the same issue, checks for spare capacity can happen before decrease happened. We would need to decrease within read lock and that is starting to get too clever. Semaphore offers solution that is simpler to verify.

**Comment by svendiedrichsen** [comment]
@pdudits After trying to think this through using a counter I couldn't myself. The seamphore is a good solution. But then we have to consider changing the MaxSize of the pool during runtime.

**Comment by svendiedrichsen** [comment]
@pdudits BTW couldn't you have used the counter like you have the Semaphore? Like counting down from maxSize?

**Comment by pdudits** [comment]
> But then we have to consider changing the MaxSize of the pool during runtime.

Oh, I thought I've seen maxSize as final. This will make things awkward, as semaphore doesn't like arbitrarily changing state

> couldn't you have used the counter like you have used the Semaphore

Yes it looks that semaphore is implemented via compare-and-swap operations itself. It just looks more explicit, but we'll see if I can accomodate for maxSize changing.

**Comment by svendiedrichsen** [comment]
@pdudits IMHO a semaphore looks like a little bit much for the problem to solve. You are not synchonizing threads at all but only counting down.

**Comment by pdudits** [comment]
@svendiedrichsen You're right, and here we've got third attempt which uses `AtomicInteger` again.

File: appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java [hunk 2]
```diff
@@ -102,16 +102,22 @@ public int addResource(final ResourceAllocator allocator, int count) throws Pool
...
                 throw new PoolingException(e.getMessage(), e);
             }
         }
         return numResAdded;
     }
 
     private boolean canGrow() {
-        return growPermit.tryAcquire();
+        int capacity = remainingCapacity.getAndUpdate((x) -> x > 0 ? x - 1 : 0);
+        return capacity > 0;
```
Comment (svendiedrichsen) [inline appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java:116]: This should be `!= 0`, shouldn't it?

**Comment by svendiedrichsen** [comment]
@pdudits This should do it. Nice job.

**Comment by pdudits** [comment]
Jenkins test please

**Review by aubi — APPROVED** [review]
The code looks good, I tried both performance and correctness testing.
